
# These are speculative; we can update as appropriate.
# Format the entire project with `cargo +nightly fmt`,
# many of these require the nightly channel.

binop_separator = "Back"
format_generated_files = false
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
match_block_trailing_comma = true
use_field_init_shorthand = true
# normalize_comments = true
overflow_delimited_expr = true
reorder_imports = true
reorder_modules = true
