mod collation;
mod db;
mod file;
mod file_exports;
mod file_imports;
mod file_resolve;
mod files;
mod legacy;
mod name;
mod parse;
mod resolver;
mod root;
mod source_graph;
mod vfs;
pub mod vfs_scan;

#[cfg(test)]
mod tests;

pub use collation::collation_files;
pub use db::Db;
pub use file::File;
pub use file_exports::ExportEntry;
pub use file_exports::FileExports;
pub use file_imports::ImportLayer;
pub use file_resolve::Resolution;
pub use files::intern_file;
pub use files::Files;
pub use legacy::semantic_index_with_source_resolver;
pub use legacy::LegacyDb;
pub use name::Name;
pub use root::url_to_root;
pub use root::Root;
pub use root::RootKind;
pub use source_graph::Package;
pub use source_graph::PackageOrigin;
pub use source_graph::Script;
pub use source_graph::SourceGraph;
pub use source_graph::SourceNode;
pub use source_graph::WorkspaceRoots;
pub use vfs::Vfs;
