name: "Amalthea Tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  linux:
    name: Unit Tests on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential r-base-dev libsodium-dev

      - name: Build
        id: amalthea-build
        run: |
            cargo build --verbose

      # Ubuntu runners already have a version of R installed.
      # Unit tests "automatically" find and set `R_HOME` if it isn't set by
      # calling `R RHOME`. See the testing version of `start_r()` for this.
      - name: Run Unit Tests
        id: amalthea-test
        run: |
            cargo test --verbose
