name: "Amalthea Tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    name: "Unit Tests on Linux (rust: ${{ matrix.config.rust }})"
    strategy:
      fail-fast: false
      matrix:
        config:
          - { rust: 'stable'  }
          - { rust: 'nightly' }
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        if: matrix.config.rust == 'nightly'

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential r-base-dev libsodium-dev

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30

      # Ubuntu runners already have a version of R installed.
      # Unit tests "automatically" find and set `R_HOME` if it isn't set by
      # calling `R RHOME`. See the testing version of `start_r()` for this.
      - name: Run Unit Tests
        id: amalthea-test
        run: |
            cargo test --verbose
