name: "Check Rust"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting:
    name: "Check formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Our `.rustfmt.toml` does use some nightly rules
      - name: "Install rustfmt"
        run: rustup component add rustfmt --toolchain nightly

      - name: "Check formatting"
        run: cargo +nightly fmt --all --check

  clippy:
    name: "Check clippy"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: "Install clippy"
        run: rustup component add clippy

      - name: Toolchain versions
        run: |
          rustc -Vv
          cargo -V
          cargo clippy -V

      - name: "Check clippy"
        run: cargo clippy --all-targets --all-features --locked -- -D warnings

  dependencies:
    name: "Check only workspace dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Check only workspace dependencies"
        run: python3 ./scripts/check-only-workspace-dependencies.py
