name: "Testing - Linux"

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    name: "Unit Tests on Linux (rust: ${{ matrix.config.rust }})"
    strategy:
      fail-fast: false
      matrix:
        config:
          - { rust: 'stable'  }
          - { rust: 'nightly' }
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        if: matrix.config.rust == 'nightly'

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsodium-dev

      - name: Build
        id: build
        run: |
            cargo build --verbose

      # Unit tests "automatically" find and set `R_HOME` if it isn't set by
      # calling `R RHOME`. See `harp::fixtures::r_test_init()`.
      - name: Run Unit Tests
        id: test
        run: |
            cargo test --verbose
