name: "Test Ark - Linux"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    name: "Rust: ${{ matrix.config.rust }}, R: ${{ matrix.config.r }}"
    strategy:
      fail-fast: false
      matrix:
        config:
          - { rust: 'stable',  r: 'release' }
          # Oldest supported R version
          - { rust: 'stable',  r: '4.2' }
          # Nightly rust
          - { rust: 'nightly', r: 'release' }
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        if: matrix.config.rust == 'nightly'

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Setup Build Environment
        run: |
          sudo apt-get update

      - name: Run Unit Tests
        id: test
        run: |
            cargo test --verbose
